version: "3.7"

networks: 
  AIservice: 
  
services:
  frontend:
    build: Streamlit_Frontend
    ports:
      - 8501:8501
    networks: 
      AIservice: 
        aliases: 
          - frontend.docker
    depends_on:
      - backend
    volumes:
        - ./Streamlit_Frontend:/app
        - ./storage:/storage

  backend:
    build: FastAPI_Backend
    ports:
      - 8000:8000
    networks: 
      AIservice: 
        aliases: 
          - backend.docker
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - ./FastAPI_Backend:/app
      - './:/src'

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  db:
    driver: local